study/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from .views import index_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index_view, name='index'),
    path('todo/', include('todo_list.urls'))
]

todo_list/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import TodoListIndexView, TodoListView, TodoListAllView, TodoListDetailView

app_name = 'todo_list'
urlpatterns = [
    path('', TodoListView.as_view(), name='index'),
    path('list/', TodoListAllView.as_view(), name='list'),
    path('<int:pk>/', TodoListDetailView.as_view(), name='detail'),
]

todo_list/models.py
from django.db import models
from django.db.models import Model


class TodoItem(Model):
    class Meta:
        verbose_name = 'TODO Item'
        ordering = ("id", )

    name = models.CharField(max_length=120)
    is_done = models.BooleanField(default=False)

    def __str__(self):
        return self.name

study/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render


def index_view(request: HttpRequest) -> HttpResponse:
    return render(request, template_name='index.html')

todo_list/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView

from .models import TodoItem


def index_view(request: HttpRequest) -> HttpResponse:
    todo_tasks = TodoItem.objects.all()
    return render(
        request,
        template_name='todo_list/index.html',
        context={'todo_tasks': todo_tasks}
    )


class TodoListIndexView(TemplateView):
    template_name = 'todo_list/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["todo_tasks"] = TodoItem.objects.all()
        return context


class TodoListView(ListView):
    template_name = "todo_list/index.html"
    queryset = TodoItem.objects.all()[:2]


class TodoListAllView(ListView):
    template_name = "todo_list/list.html"
    model = TodoItem


class TodoListDetailView(DetailView):
    model = TodoItem

study/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Base HTML
        {% endblock title %}
    </title>
</head>
<body>
{% include 'components/header.html' %}
{% block body %}
    Welcome!!!
{% endblock body %}
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Base HTML
        {% endblock title %}
    </title>
</head>
<body>
{% include 'components/header.html' %}
{% block body %}
    Welcome!!!
{% endblock body %}
<footer>
    &copy; Company
    {% block footer %}
        <u>Main Base</u>
    {% endblock footer %}
</footer>
</body>
</html>

templates/components/header.html
<header>
    <ul>
        <li>
            <a href="{% url 'index' %}">Base</a>
            <a href="{% url 'todo_list:index' %}">TO-DO</a>
        </li>
    </ul>
</header>

templates/index.html
{% extends 'base.html' %}
{% block title %}
    STUDY
{% endblock title %}

{% block body %}
    <h1>Hello, world</h1>
    <h2>Time is {% now "jS F Y H:i" %}</h2>
{% endblock body %}

todo_list/templates/todo_list/base.html
{% extends 'base.html' %}

{% block footer %}
    <u>TODO Base</u>
{% endblock footer %}

todo_list/templates/todo_list/components/task_list.html
<ul>
    {% for task in object_list %}
        <li>
            <a href="{% url 'todo_list:detail' pk=task.pk %}">
                <p>{{ task.name }}</p>
                {% if task.is_done %}
                    <input type="checkbox" checked>
                {% else %}
                    <input type="checkbox">
                {% endif %}
            </a>
        </li>
    {% endfor %}
</ul>

todo_list/templates/todo_list/index.html
{% extends 'todo_list/base.html' %}

{% block title %}
    TODO List App
{% endblock title %}

{% block body %}
    <h1>TODO Tasks:</h1>
    <a href="{% url 'todo_list:list' %}">All Tasks</a>
    {% include 'todo_list/components/task_list.html' %}
{% endblock %}

todo_list/templates/todo_list/list.html
{% extends 'base.html' %}

{% block title %}
    TODO List TASKS:
{% endblock title %}

{% block body %}
    <h1>ALL TODO Tasks:</h1>
    {% include 'todo_list/components/task_list.html' %}
{% endblock %}

todo_list/templates/todo_list/todoitem_detail.html
{% extends 'base.html' %}

{% block body %}
    <h1>{{ object.name }}</h1>
    <p>Is done: 
        {% if object.is_done %}
            YES!!!
        {% else %}
            NO!!!
        {% endif %}</p>
{% endblock body %}